<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Central Standard Time">
<General productName="QuickTest Professional" productVer="11.00" os="Windows 7" host="WUSAS250451-ZHV"><DocLocation><![CDATA[C:\automation\Scripts\WorkFlowAppointments]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[WorkFlowAppointments]]></DName>
<Res><![CDATA[Run_032112_1252]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[3/21/2012 - 12:52:55]]></Time>
<TimeTick>1332352375</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Details>
<Time><![CDATA[3/21/2012 - 12:52:55]]></Time>
<TimeTick>1332352375</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[Run "iexplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj ><![CDATA[Info]]></Obj>
<Details ><![CDATA[Opening IE with url https://appointments-dev.bankofamerica.com/associates/login.aspx]]></Details>
<Time><![CDATA[3/21/2012 - 12:52:58]]></Time>
<TimeTick>1332352378</TimeTick>
<NodeArgs eType="User" icon="6" nRep="12" >
<Disp><![CDATA[Info]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Smart Lobby-LoginPage]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[3/21/2012 - 12:52:58]]></Time>
<TimeTick>1332352378</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Smart Lobby-LoginPage]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[3/21/2012 - 12:52:58]]></Time>
<TimeTick>1332352378</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Smart Lobby-LoginPage.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/21/2012 - 12:52:58]]></Time>
<TimeTick>1332352378</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="17" >
<Disp><![CDATA[Smart Lobby-LoginPage.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Smart Lobby-LoginPage.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["enabled", 1, True, 2000]]></Details>
<Time><![CDATA[3/21/2012 - 12:52:58]]></Time>
<TimeTick>1332352378</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="19" >
<Disp><![CDATA[Smart Lobby-LoginPage.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Smart Lobby-LoginPage.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/21/2012 - 12:52:58]]></Time>
<TimeTick>1332352378</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="21" >
<Disp><![CDATA[Smart Lobby-LoginPage.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="16" >
<Disp><![CDATA[Smart Lobby-LoginPage]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="15" >
<Disp><![CDATA[Smart Lobby-LoginPage]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj ><![CDATA[Pass]]></Obj>
<Details ><![CDATA[Navigated to Login Page -  Smart Lobby-LoginPage [Page] displayed.]]></Details>
<Time><![CDATA[3/21/2012 - 12:52:58]]></Time>
<TimeTick>1332352378</TimeTick>
<NodeArgs eType="User" icon="6" nRep="22" status="Passed" >
<Disp><![CDATA[Pass]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj ><![CDATA[Error]]></Obj>
<Details ><![CDATA[Email Send failed. Subject line: 'Automation Smoke Test Started', Error message: The server rejected the sender address. The server response was: 550 5.7.1 Client does not have permissions to send as this sender<BR>]]></Details>
<Time><![CDATA[3/21/2012 - 12:52:59]]></Time>
<TimeTick>1332352379</TimeTick>
<NodeArgs eType="User" icon="6" nRep="23" status="Failed" >
<Disp><![CDATA[Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Smart Lobby-LoginPage]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:00]]></Time>
<TimeTick>1332352380</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Smart Lobby-LoginPage]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:00]]></Time>
<TimeTick>1332352380</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[UserName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["masteradmin@ncr.com"]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:00]]></Time>
<TimeTick>1332352380</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="28" >
<Disp><![CDATA[UserName.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="27" >
<Disp><![CDATA[Smart Lobby-LoginPage]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="26" >
<Disp><![CDATA[Smart Lobby-LoginPage]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj ><![CDATA[Info]]></Obj>
<Details ><![CDATA[Entered masteradmin@ncr.com in UserName [WebEdit]]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:00]]></Time>
<TimeTick>1332352380</TimeTick>
<NodeArgs eType="User" icon="6" nRep="29" >
<Disp><![CDATA[Info]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Smart Lobby-LoginPage]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:00]]></Time>
<TimeTick>1332352380</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Smart Lobby-LoginPage]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:00]]></Time>
<TimeTick>1332352380</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["masteradmin"]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:00]]></Time>
<TimeTick>1332352380</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="34" >
<Disp><![CDATA[Password.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="33" >
<Disp><![CDATA[Smart Lobby-LoginPage]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="32" >
<Disp><![CDATA[Smart Lobby-LoginPage]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj ><![CDATA[Info]]></Obj>
<Details ><![CDATA[Entered masteradmin in Password [WebEdit]]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:00]]></Time>
<TimeTick>1332352380</TimeTick>
<NodeArgs eType="User" icon="6" nRep="35" >
<Disp><![CDATA[Info]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Smart Lobby-LoginPage]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:00]]></Time>
<TimeTick>1332352380</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Smart Lobby-LoginPage]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:00]]></Time>
<TimeTick>1332352380</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[LoginBtn.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:00]]></Time>
<TimeTick>1332352380</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="40" >
<Disp><![CDATA[LoginBtn.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="39" >
<Disp><![CDATA[Smart Lobby-LoginPage]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Windows Internet Explorer.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:02]]></Time>
<TimeTick>1332352382</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="41" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Windows Internet Explorer.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Windows Internet Explorer.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:02]]></Time>
<TimeTick>1332352382</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="43" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Windows Internet Explorer.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Windows Internet Explorer]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:04]]></Time>
<TimeTick>1332352384</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:04]]></Time>
<TimeTick>1332352384</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="46" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Yes.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="45" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Windows Internet Explorer]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="38" >
<Disp><![CDATA[Smart Lobby-LoginPage]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[SmartLobby]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:09]]></Time>
<TimeTick>1332352389</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[SmartLobby]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:09]]></Time>
<TimeTick>1332352389</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[SmartLobby.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:09]]></Time>
<TimeTick>1332352389</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="51" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SmartLobby.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[SmartLobby.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["enabled", 1, True, 2000]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:09]]></Time>
<TimeTick>1332352389</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="53" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SmartLobby.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[SmartLobby.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:09]]></Time>
<TimeTick>1332352389</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="55" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SmartLobby.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[ActivityMonitoring.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:09]]></Time>
<TimeTick>1332352389</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="56" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[ActivityMonitoring.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="50" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SmartLobby]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="49" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SmartLobby]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj ><![CDATA[Pass]]></Obj>
<Details ><![CDATA[Smart Lobby Home page launched successfully SmartLobby [Page] displayed. Validation object, ActivityMonitoring [Image] found.]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:09]]></Time>
<TimeTick>1332352389</TimeTick>
<NodeArgs eType="User" icon="6" nRep="57" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Pass]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[SmartLobby]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:09]]></Time>
<TimeTick>1332352389</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[SmartLobby]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:09]]></Time>
<TimeTick>1332352389</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[ActivityMonitoring.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:09]]></Time>
<TimeTick>1332352389</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="62" >
<Disp><![CDATA[ActivityMonitoring.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[SmartLobby.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:11]]></Time>
<TimeTick>1332352391</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="65" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SmartLobby.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[SmartLobby.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["enabled", 1, True, 2000]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:11]]></Time>
<TimeTick>1332352391</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="67" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SmartLobby.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[SmartLobby.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:11]]></Time>
<TimeTick>1332352391</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="69" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SmartLobby.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Frame_User Permissions]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:11]]></Time>
<TimeTick>1332352391</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Frame_User Permissions.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:11]]></Time>
<TimeTick>1332352391</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="71" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Frame_User Permissions.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="70" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Frame_User Permissions]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="61" >
<Disp><![CDATA[SmartLobby]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="60" >
<Disp><![CDATA[SmartLobby]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj ><![CDATA[Pass]]></Obj>
<Details ><![CDATA[Navigated to Login View Selection Page. SmartLobby [Page] displayed. Validation object, Frame_User Permissions [Frame] found.]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:12]]></Time>
<TimeTick>1332352392</TimeTick>
<NodeArgs eType="User" icon="6" nRep="72" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Pass]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj ><![CDATA[Info]]></Obj>
<Details ><![CDATA[Selecting View:LOBBY]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:12]]></Time>
<TimeTick>1332352392</TimeTick>
<NodeArgs eType="User" icon="6" nRep="73" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Info]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[SmartLobby]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:12]]></Time>
<TimeTick>1332352392</TimeTick>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[SmartLobby]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:12]]></Time>
<TimeTick>1332352392</TimeTick>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Frame_User Permissions]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:12]]></Time>
<TimeTick>1332352392</TimeTick>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[imgLobby.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:12]]></Time>
<TimeTick>1332352392</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="79" >
<Disp><![CDATA[imgLobby.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="78" >
<Disp><![CDATA[Frame_User Permissions]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[SmartLobby.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:14]]></Time>
<TimeTick>1332352394</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="82" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SmartLobby.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[SmartLobby.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["enabled", 1, True, 2000]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:14]]></Time>
<TimeTick>1332352394</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="84" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SmartLobby.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[SmartLobby.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:14]]></Time>
<TimeTick>1332352394</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="86" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SmartLobby.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Frame_ActivityManager]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:14]]></Time>
<TimeTick>1332352394</TimeTick>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Frame_ActivityManager.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:14]]></Time>
<TimeTick>1332352394</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="88" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Frame_ActivityManager.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="87" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Frame_ActivityManager]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="77" >
<Disp><![CDATA[SmartLobby]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="76" >
<Disp><![CDATA[SmartLobby]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj ><![CDATA[Pass]]></Obj>
<Details ><![CDATA[Navigated to LOBBY SmartLobby [Page] displayed. Validation object, Frame_ActivityManager [Frame] found.]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:14]]></Time>
<TimeTick>1332352394</TimeTick>
<NodeArgs eType="User" icon="6" nRep="89" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Pass]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[SmartLobby]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:14]]></Time>
<TimeTick>1332352394</TimeTick>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[SmartLobby]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:14]]></Time>
<TimeTick>1332352394</TimeTick>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[AppointmentManager.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:14]]></Time>
<TimeTick>1332352394</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="94" >
<Disp><![CDATA[AppointmentManager.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Frame_AppointmentManager]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:17]]></Time>
<TimeTick>1332352397</TimeTick>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Frame_AppointmentManager.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:17]]></Time>
<TimeTick>1332352397</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="97" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Frame_AppointmentManager.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="96" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Frame_AppointmentManager]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="93" >
<Disp><![CDATA[SmartLobby]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="92" >
<Disp><![CDATA[SmartLobby]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj ><![CDATA[Pass]]></Obj>
<Details ><![CDATA[Navigated to Appointment Manager Page Frame_AppointmentManager [Frame] displayed.]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:17]]></Time>
<TimeTick>1332352397</TimeTick>
<NodeArgs eType="User" icon="6" nRep="98" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Pass]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[SmartLobby]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:17]]></Time>
<TimeTick>1332352397</TimeTick>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[SmartLobby]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:17]]></Time>
<TimeTick>1332352397</TimeTick>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[ShowLocator.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:17]]></Time>
<TimeTick>1332352397</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="102" >
<Disp><![CDATA[ShowLocator.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[ShowHideLocatorArrow.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:17]]></Time>
<TimeTick>1332352397</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="105" >
<Disp><![CDATA[ShowHideLocatorArrow.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[HideLocator.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:21]]></Time>
<TimeTick>1332352401</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="112" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[HideLocator.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[BankLocation_TreeView]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:26]]></Time>
<TimeTick>1332352406</TimeTick>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[[ Expand Austin   ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:26]]></Time>
<TimeTick>1332352406</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="117" >
<Disp><![CDATA[[ Expand Austin   ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[[ Arboretum ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:28]]></Time>
<TimeTick>1332352408</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="118" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ Arboretum ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[[ Arboretum ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:28]]></Time>
<TimeTick>1332352408</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="120" >
<Disp><![CDATA[[ Arboretum ].Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="116" >
<Disp><![CDATA[BankLocation_TreeView]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[Frame_AppointmentManager]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:31]]></Time>
<TimeTick>1332352411</TimeTick>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[Schedule.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:31]]></Time>
<TimeTick>1332352411</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="124" >
<Disp><![CDATA[Schedule.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="123" >
<Disp><![CDATA[Frame_AppointmentManager]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="101" >
<Disp><![CDATA[SmartLobby]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="100" >
<Disp><![CDATA[SmartLobby]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74">
<Obj plainTxt="False" ><![CDATA[SelectBankTopic_Step2]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:37]]></Time>
<TimeTick>1332352417</TimeTick>
<Step rID="T75">
<Obj plainTxt="False" ><![CDATA[SelectBankTopic_Step2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:37]]></Time>
<TimeTick>1332352417</TimeTick>
<Step rID="T76">
<Obj plainTxt="False" ><![CDATA[SelectBankTopic_Step2.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:37]]></Time>
<TimeTick>1332352417</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="129" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SelectBankTopic_Step2.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T77">
<Obj plainTxt="False" ><![CDATA[SelectBankTopic_Step2.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["enabled", 1, True, 2000]]></Details>
<Time><![CDATA[3/21/2012 - 12:53:37]]></Time>
<TimeTick>1332352417</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="131" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SelectBankTopic_Step2.WaitProperty]]></Disp>
</NodeArgs>